name: Publish Package to npmjs

on:
  release:
    types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Build
        run: pnpm build

      - name: NPM Publish
        run: npm publish
